const SEARCH_IMAGE_ADD = 'SEARCH_IMAGE_ADD';
const SEARCH_IMAGE_IS_LOADING = 'SEARCH_IMAGE_IS_LOADING';
const SEARCH_IMAGE_ERROR = 'SEARCH_IMAGE_ERROR';
const DEFAULT_SEARCH_IMAGE_ADD = 'DEFAULT_SEARCH_IMAGE_ADD';

const SELECT_IMAGE = 'SELECT_IMAGE';

// for quotes in quotes component 
const GET_QUOTES = 'GET_QUOTES';
const GET_QUOTES_IS_LOADING = 'GET_QUOTES_IS_LOADING';
const GET_QUOTES_ERROR = 'GET_QUOTES_ERROR';

// for text in editor 
const EDITOR_ADD_TEXT = 'EDITOR_ADD_TEXT';
const EDITOR_DELETE_TEXT = 'EDITOR_DELETE_TEXT';

// for select shape in editor 
const SELECT_SHAPE_IN_EDITOR = 'SELECT_SHAPE_IN_EDITOR';

export {
  SEARCH_IMAGE_ADD,
  SEARCH_IMAGE_IS_LOADING,
  SEARCH_IMAGE_ERROR,
  DEFAULT_SEARCH_IMAGE_ADD,
  SELECT_IMAGE,
  GET_QUOTES,
  GET_QUOTES_IS_LOADING,
  GET_QUOTES_ERROR,
  EDITOR_ADD_TEXT,
  SELECT_SHAPE_IN_EDITOR,
  EDITOR_DELETE_TEXT
}