const SEARCH_IMAGE_ADD = 'SEARCH_IMAGE_ADD';
const SEARCH_IMAGE_IS_LOADING = 'SEARCH_IMAGE_IS_LOADING';
const SEARCH_IMAGE_ERROR = 'SEARCH_IMAGE_ERROR';
const DEFAULT_SEARCH_IMAGE_ADD = 'DEFAULT_SEARCH_IMAGE_ADD';

const SELECT_IMAGE = 'SELECT_IMAGE';

const GET_QUOTES = 'GET_QUOTES';
const GET_QUOTES_IS_LOADING = 'GET_QUOTES_IS_LOADING';
const GET_QUOTES_ERROR = 'GET_QUOTES_ERROR';

export {
  SEARCH_IMAGE_ADD,
  SEARCH_IMAGE_IS_LOADING,
  SEARCH_IMAGE_ERROR,
  DEFAULT_SEARCH_IMAGE_ADD,
  SELECT_IMAGE,
  GET_QUOTES,
  GET_QUOTES_IS_LOADING,
  GET_QUOTES_ERROR
}