const SEARCH_IMAGE_ADD = 'SEARCH_IMAGE_ADD';
const SEARCH_IMAGE_IS_LOADING = 'SEARCH_IMAGE_IS_LOADING';
const DEFAULT_SEARCH_IMAGE = 'DEFAULT_SEARCH_IMAGE';

const SELECT_IMAGE = 'SELECT_IMAGE';

export {
  SEARCH_IMAGE_ADD,
  SEARCH_IMAGE_IS_LOADING,
  DEFAULT_SEARCH_IMAGE,
  SELECT_IMAGE
}